name: Bonjour
on: [push]
jobs:
  dire_bonjour:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get install -y cowsay
      - run: cat README.md | cowsay -f dragon-and-cow # Affiche le contenu du fichier `README.md` à la base du dépôt